stages:
  run_msa:
    cmd: python scripts/run_msa.py
    params:
      - use_msa
      - msa_creation.msa_mode

      # if msa_mode is starting_sequences
      - msa_creation.starting_sequences.prealigned
      - msa_creation.starting_sequences.add_training_sequences
      - msa_creation.starting_sequences.activity_targets
      - msa_creation.starting_sequences.activity_threshold

      # if msa_mode is jackhmmer
      - msa_creation.jackhmmer.seqdb
      - msa_creation.jackhmmer.iterations
      - msa_creation.jackhmmer.domain_threshold
      - msa_creation.jackhmmer.sequence_threshold
      - msa_creation.jackhmmer.use_bitscores
      - msa_creation.jackhmmer.sequence_identity_filter
      - msa_creation.jackhmmer.cpus
      - msa_creation.jackhmmer.mx
    deps:
      - data/starting_sequences.fa
      - data/starting_sequences.a3m
      - data/experimental_data.csv
      - data/wt.fa
    outs: 
      - data/run_msa/
    metrics:
      - data/metrics/run_msa.json:
          cache: false