name: aidep
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - hmmer
  - mafft
  - pip
  - pip:
    - dvc
    - numpy<1.20.0
    - scikit-learn
    - pandas
    - numba<
    - tqdm
    - evcouplings @ git+https://github.com/debbiemarkslab/EVcouplings@af27842
    - ruamel-yaml<0.18.0


