name: aidep
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python<=3.10
  - hmmer=3.3.2
  - mmseqs2
  - plmc
  - cffi
  - mafft
  - pip
  - foldseek
  - pip:
    - numpy<2.0
    - scikit-learn
    - pandas
    - h5py
    - tqdm
    - biopython==1.84


