name: aidep
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - numpy<1.20
  - pandas
  - hmmer
  - scikit-learn
  - mafft
  - pip
  - pip:
    - dvc
    - tqdm
    - evcouplings @ git+https://github.com/debbiemarkslab/EVcouplings@af27842
    - ruamel.yaml<0.18.0


