name: aidep
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - numpy
  - pandas
  - hmmer
  - scikit-learn
  - pip
  - pip:
    - dvc
    - tqdm
    - evcouplings @ git+https://github.com/debbiemarkslab/EVcouplings@af27842


