name: aidep
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - hmmer
  - plmc
  - cffi
  - mafft
  - pip
  - foldseek
  - pip:
    - dvc
    - numpy
    - scikit-learn
    - pandas
    - h5py
    - numba
    - tqdm
    - evcouplings @ git+https://github.com/debbiemarkslab/EVcouplings@374d4c5
    - ruamel-yaml<0.18.0
    - biopython==1.84


