jackhmmer:
  seqdb: /kfs2/projects/bpms/ekomp_tmp/datasets/uniref/uniref100.fasta
  iterations: 5
  evalue: 0.0001
  tvalue: 0.5
  use_bitscores: true
  cpus: 4
  mx: 'BLOSUM62'
  popen: 0.02
  pextend: 0.4
msaprocessing:
  theta: 0.2
  use_weights: true
  preprocess: true
  threshold_sequence_frac_gaps: 0.5
  threshold_focus_cols_frac_gaps: 0.5
  remove_sequences_with_indeterminate_AA_in_focus_cols: true