name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2


    - name: Set up conda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda config --set channel_priority flexible
        conda env update --file environment.yaml --name base
        conda install pytest pytest-cov

    - name: Run tests with pytest and coverage
      run: |
        pytest -v -m "not slow and not optional" --cov=aide_predict --cov-report=xml --cov-config=.coveragerc


    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true